spring.application.name=questoes-api
spring.datasource.url=x
spring.datasource.username=x
spring.datasource.password=x

spring.security.oauth2.client.registration.google.client-id=x
spring.security.oauth2.client.registration.google.client-secret=x
spring.security.oauth2.client.registration.google.scope=email,profile

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.security.oauth2.client.registration.google.client-id=x
spring.security.oauth2.client.registration.google.client-secret=x
spring.security.oauth2.client.registration.google.scope=email,profile